$(document).ready(function () {

  var data = {
    selling: [
      "ABD",
      "Air Conditioner",
      "Alarm Clock",
      "Aloe",
      "Alpine Bed",
      "Alpine Chair",
      "Alpine Closet",
      "Alpine Dresser",
      "Alpine Kitchen Cart",
      "Alpine Lamp",
      "Alpine Low Table",
      "Alpine Panel",
      "Alpine Shelf",
      "Alpine Sofa",
      "Aluminum Briefcase",
      "Amazing Machine",
      "Amp",
      "Anatomical Model",
      "Anchor",
      "Antique Clock",
      "Arc de Triomphe",
      "Arcade Machine",
      "Aroma Pot",
      "Arrow Sign",
      "Arwing",
      "Asteroid",
      "Astro Bed",
      "Astro CD Player",
      "Astro Chair",
      "Astro Clock",
      "Astro Closet",
      "Astro Dresser",
      "Astro Lamp",
      "Astro Shelf",
      "Astro Sofa",
      "Astro Table",
      "Astro TV",
      "Aurora Screen",
      "Automatic Washer",
      "Ayers Rock",
      "Azalea Bonsai",
      "Azalea Stool",
      "Baby Bear",
      "Baby Bed",
      "Baby Panda",
      "Backpack",
      "Backyard Pool",
      "Bagpipes",
      "Ball Catcher",
      "Ball Return",
      "Balloon Bed",
      "Balloon Chair",
      "Balloon Clock",
      "Balloon Closet",
      "Balloon Dresser",
      "Balloon Lamp",
      "Balloon Sofa",
      "Balloon Table",
      "Balloon TV",
      "Balloon Vanity",
      "Balloon-Dog Lamp",
      "Bamboo Grass",
      "Barbecue",
      "Barber's Pole",
      "Barrel",
      "Basketball Hoop",
      "Bass",
      "Bath Mat",
      "Bathroom Sink",
      "Bathroom Stall",
      "Bathtub",
      "Beach Chair",
      "Beach Table",
      "Beacon Fire",
      "Bear Pole",
      "Beetle Chair",
      "Bell Knickknack",
      "Berliner",
      "Big Ben",

      "Bilboquet",
      "Bill Blaster",
      "Billiard Table",
      "Bingo Wheel",
      "Bird Feeder",
      "Birdbath",
      "Birdcage",
      "Birdhouse",
      "Birthday Cake",
      "Birthday Candles",
      "Birthday Sign",
      "Birthday Table",
      "Bishop",
      "Biwa Lute",
      "Black Katana",
      "Block",
      "Blue Bed",
      "Blue Bench",
      "Blue Bookcase",
      "Blue Bureau",
      "Blue Cabinet",
      "Blue Certificate",
      "Blue Chair",
      "Blue Clock",
      "Blue Corner",
      "Blue Dresser",
      "Blue Falcon",
      "Blue Table",
      "Blue Vase",
      "Blue Wall Shelf",
      "Blue Wardrobe",
      "Bobsled",
      "Bonfire",
      "Boomerang",
      "Bottled Ship",
      "Bow",
      "Bowling Pins",
      "Box Corner Sofa",
      "Box of Chocolates",
      "Box of Tissues",
      "Box Sofa",
      "Boxed Figurine",
      "Boxing Barricade",
      "Boxing Mat",
      "Bread Box",
      "Breaker",
      "Broken Post",
      "Bromeliaceae",
      "Bronze Bug Trophy",
      "Bronze Fish Trophy",
      "Brown Pot",
      "Buche de Noel",
      "Bucket",
      "Bug Zapper",
      "Bunk Bed",
      "Bureom",
      "Butterfly Machine",
      "Cabana Armchair",
      "Cabana Bed",
      "Cabana Bookcase",
      "Cabana Chair",
      "Cabana Dresser",
      "Cabana Lamp",
      "Cabana Screen",
      "Cabana Table",
      "Cabana Vanity",
      "Cabana Wall Radio",
      "Cabana Wardrobe",
      "Cabin Armchair",
      "Cabin Bed",
      "Cabin Bookcase",
      "Cabin Chair",
      "Cabin Clock",
      "Cabin Couch",
      "Cabin Dresser",
      "Cabin Low Table",
      "Cabin Table",
      "Cabin Wall Clock",
      "Cabin Wardrobe",
      "Cacao Tree",
      "Cactus",
      "Caladium",
      "Camp Stove",
      "Campfire",
      "Campfire Cookware",
      "Candle",
      "Candy Jar",
      "Candy Machine",
      "Capsule-Toy Machine",
      "Captain's Monitor",
      "Card Bed",
      "Card Chair",
      "Card Closet",
      "Card Dresser",
      "Card Lamp",
      "Card Screen",
      "Card Shelf",
      "Card Sofa",
      "Card Table",
      "Card Tower",
      "Card Wall Clock",
      "Cardboard Bed",
      "Cardboard Box",
      "Cardboard Chair",
      "Cardboard Closet",
      "Cardboard Sofa",
      "Cardboard Table",
      "Cash Register",
      "Cassette Player",
      "Caterpillar Sofa",
      "CD Player",
      "CD Shelf",
      "Cello",
      "Cement Mixer",
      "Ceramic Hot Pot",
      "Chaise Lounge",
      "Chalkboard",
      "Checkout Counter",
      "Chocolate Cake",
      "Chocolate Fountain",
      "Cicada Stereo",
      "Circle Banner",
      "Clackercart",
      "Classic Bed",
      "Classic Bookcase",
      "Classic Buffet",
      "Classic Chair",
      "Classic Clock",
      "Classic Desk",
      "Classic Sofa",
      "Classic Table",
      "Classic Vanity",
      "Classic Wall Shelf",
      "Classic Wardrobe",
      "Claw-Foot Tub",
      "Clay Furnace",
      "Clear Model",
      "Clothes Closet",
      "Clothesline Pole",
      "Coat Hanger",
      "Coconut Palm",
      "Coffee Cup",
      "Coffee Grinder",
      "Coffeemaker",
      "Coin",
      "Colorful Wheel",
      "Common Bed",
      "Common Chair",
      "Compass",
      "Complex Machine",
      "Computer",
      "Computer Desk",
      "Conga Drum",
      "Conveyor-Belt Sushi",
      "Cool Globe",
      "Copy Machine",
      "Corinthian Post",
      "Corkboard",
      "Corn Plant",
      "Cornucopia",
      "Cosmos Fan",
      "Country Guitar",
      "Covered Wagon",
      "Cow Skull",
      "Crab Clock",
      "Cradle",
      "Crane Game",
      "Cream and Sugar",
      "Cream Sofa",
      "Creepy Bat Stone",
      "Creepy Cauldron",
      "Creepy Clock",
      "Creepy Coffin",
      "Creepy Crystal",
      "Creepy Skeleton",
      "Creepy Statue",
      "Creepy Stone",
      "Crew Member's Seat",
      "Crew's Monitor",
      "Croton",
      "Cubbyhole",
      "Cube Clock",
      "Cuckoo Clock",
      "Cucumber Horse",
      "Cupid Bench",
      "Curling Stone",
      "Cushion",
      "Dab Table",
      "Daffodil",
      "Dala Horse",
      "Dango",
      "Dartboard",
      "Deer Scare",
      "Deluxe Range",
      "Deluxe Washer",
      "Dentist's Chair",
      "Desert Cactus",
      "Desk Light",
      "Dessert Case",
      "Detour Arrow",
      "Dharma",
      "Dice Stereo",
      "Digital-Photo Frame",
      "Director's Chair",
      "Dishwasher",
      "Display Shelf",
      "Display Stand",
      "Diver Dan",
      "DJ's Turntable",
      "Djimbe Drum",
      "Doghouse",
      "Dollhouse",
      "Dolly",
      "Donut Stool",
      "Dracaena",
      "Dream Catcher",
      "Drinking Fountain",
      "Drip Pail",
      "Drum Set",
      "Eagle Pole"],

    buying: ["Ebony Piano",
      "Editor's Chair",
      "Editor's Desk",
      "Effects Rack",
      "Egg Basket",
      "Egg Bed",
      "Egg Bench",
      "Egg Chair",
      "Egg Clock",
      "Egg Dresser",
      "Egg Lamp",
      "Egg Stereo",
      "Egg Table",
      "Egg Toy Set",
      "Egg TV",
      "Egg Wardrobe",
      "Eggplant Cow",
      "Eiffel Tower",
      "Eight Lamp",
      "Elder Mask",
      "Electric Guitar",
      "Electric Kettle",
      "Elephant Slide",
      "Espresso Maker",
      "Executive Toy",
      "Exercise Bike",
      "Exhibit Partition",
      "Exit Sign",
      "Exotic Bed",
      "Exotic Bench",
      "Exotic Bureau",
      "Exotic Chair",
      "Exotic Chest",
      "Exotic End Table",
      "Exotic Lamp",
      "Exotic Screen",
      "Exotic Table",
      "Exotic Wall Shelf",
      "Exotic Wardrobe",
      "Extinguisher",
      "Fan",
      "Fan Palm",
      "Fancy Doll",
      "Fancy Frame",
      "Female Mask",
      "Festival Lantern",
      "Festive Wreath",
      "Fire Bar",
      "Fire Flower",
      "Fire Hydrant",
      "Firefly Lamp",
      "Fireplace",
      "Fish Grill",
      "Five Lamp",
      "Flashy-Flower Sign",
      "Flat Display Case",
      "Flat-Screen TV",
      "Florence Flask",
      "Flounder Table",
      "Flower Bouquet",
      "Flower Chair",
      "Flower Table",
      "Flying Saucer",
      "Folding Chair",
      "Folk Guitar",
      "Foosball Table",
      "Football-Fish Lamp",
      "Four Lamp",
      "Freezer",
      "Frog-Woman Pole",
      "Froggy Chair",
      "Fruit Basket",
      "Game Shelf",
      "Game-Show Stand",
      "Garbage Can",
      "Garbage Pail",
      "Garden Gnome",
      "Gas Pump",
      "Gaudi's Lizard",
      "General's Fan",
      "General's Stool",
      "Genie's Lamp",
      "Gerbera",
      "Giant Dharma",
      "Giraffe Ruler",
      "Glass Display Case",
      "Glass-Top Table",
      "Globe",
      "Go Board",
      "Goal Pole",
      "Gold Bug Trophy",
      "Gold Fish Trophy",
      "Gold HHA Plaque",
      "Gold HHA Trophy",
      "Gold House Model",
      "Gold Stereo",
      "Golden Bed",
      "Golden Bench",
      "Golden Chair",
      "Golden Clock",
      "Golden Closet",
      "Golden Dresser",
      "Golden Man",
      "Golden Screen",
      "Golden Table",
      "Golden Wall Torch",
      "Golden Woman",
      "Golf Bag",
      "Gorgeous Bed",
      "Gorgeous Chest",
      "Gorgeous Closet",
      "Gorgeous Counter",
      "Gorgeous Desk",
      "Gorgeous Lamp",
      "Gorgeous Seat",
      "Gorgeous Sofa",
      "Gorgeous Stool",
      "Gorgeous Table",
      "Gorgeous Wall Clock",
      "Gracie Bed",
      "Gracie Bench",
      "Gracie Chair",
      "Gracie Chest",
      "Gracie Desk",
      "Gracie Lamp",
      "Gracie Low Table",
      "Gracie Shelf",
      "Gracie Wagon",
      "Gracie Wall Clock",
      "Gracie Wardrobe",
      "Grapefruit Table",
      "Grass Standee",
      "Green Bed",
      "Green Bench",
      "Green Chair",
      "Green Counter",
      "Green Desk",
      "Green Dresser",
      "Green Lamp",
      "Green Pantry",
      "Green Shell",
      "Green Table",
      "Green Wall Clock",
      "Green Wardrobe",
      "Hammock",
      "Hamster Cage",
      "Handcart",
      "Harp",
      "Harpsichord",
      "Hearth",
      "Hedge Standee",
      "Helm",
      "HHA Pennant",
      "Hi-Fi Stereo",
      "Hibachi",
      "Hibiscus",
      "Hibiscus Clock",
      "High-End Stereo",
      "High-Jump Mat",
      "Holiday Stocking",
      "Holly Bonsai",
      "Hologram Machine",
      "Home-Computer Rack",
      "Homework Set",
      "Honeybee Chest",
      "Hospital Bed",
      "Hospital Screen",
      "Hospital TV",
      "Hot Plate",
      "Hourglass",
      "Hula Doll",
      "Humidifier",
      "Hurdle",
      "Hydrangea Bed",
      "Ice Bed",
      "Ice Chair",
      "Ice Clock",
      "Ice Closet",
      "Ice Dresser",
      "Ice Lamp",
      "Ice Shelf",
      "Ice Side Table",
      "Ice Sofa",
      "Ice Table",
      "Ice Vanity",
      "Ice-Cream Case",
      "Incense Burner",
      "Ionian Post",
      "Iron Frame",
      "Ironing Set",
      "IV Drip",
      "Jack-in-the-Box",
      "Jackhammer",
      "Jasmine Bonsai",
      "Jellyfish Lamp",
      "Jingle Bed",
      "Jingle Chair",
      "Jingle Clock",
      "Jingle Dresser",
      "Jingle Lamp",
      "Jingle Piano",
      "Jingle Shelves",
      "Jingle Sofa",
      "Jingle Table",
      "Jingle TV",
      "Jingle Wardrobe",
      "Jolly Roger",
      "Jomon Pottery",
      "Judge's Bell",
      "Juicy-Apple Clock",
      "Juicy-Apple TV",
      "Jukebox",
      "Kagamimochi",
      "Karaoke System",
      "Kart",
      "Kayak",
      "Keg",
      "Kettle",
      "Kiddie Bed",
      "Kiddie Bookcase",
      "Kiddie Bureau",
      "Kiddie Chair",
      "Kiddie Clock",
      "Kiddie Couch",
      "Kiddie Dresser",
      "Kiddie Stereo",
      "Kiddie Table",
      "Kiddie Wall Clock",
      "Kiddie Wardrobe",
      "Kinderdijk Windmill",
      "King",
      "Kitchen Corner",
      "Kitchen Island",
      "Kitchen Scale",
      "Kitchen Sink",
      "Kitschy Clock",
      "Kiwi Stool",
      "Knight",
      "Kokeshi Doll",
      "Kotatsu",
      "Lab Bench",
      "Lab Chair",
      "Lady Palm",
      "Ladybug Chair",
      "Lantern",
      "Laptop",
      "Large Alpine Table",
      "Large Bookshelf",
      "Large Magazine Rack",
      "Large Space Console",
      "Lat Pulldown Machine",
      "Lava Lamp",
      "Lawn Chair",
      "Lawn Mower",
      "Lazy-Susan Table",
      "LED Display",
      "Left Platform",
      "Lefty Desk",
      "Lefty Lucky Cat",
      "Lemon Table",
      "Letter Set",
      "Life Preserver",
      "Life Ring",
      "Lift Chair",
      "Lily Lamp",
      "Lily Record Player",
      "Lily-Pad Table",
      "Loom",
      "Lotus Lamp",
      "Love Tester",
      "Lovely Armoire",
      "Lovely Bed",
      "Lovely Chair",
      "Lovely Doll",
      "Lovely Dresser",
      "Lovely End Table",
      "Lovely Kitchen",
      "Lovely Lamp",
      "Lovely Love Seat",
      "Lovely Phone",
      "Lovely Table",
      "Lovely Vanity",
      "Lovely Wall Clock",
      "Low Screen",
      "Lucky Black Cat",
      "Lucky Cat",
      "Lucky Frog",
      "Lucky Gold Cat",
      "Lunar Lander",
      "Lunar Rover",
      "Lunch Tray",
      "Mahjong Table",
      "Makeup Case",
      "Mama Bear",
      "Mama Panda",
      "Mama Polar Bear",
      "Manhole Cover",
      "Manneken Pis",
      "Maple Bonsai",
      "Marshmallow Chair",
      "Massage Chair",
      "Master Sword",
      "Matryoshka",
      "Medicine Chest",
      "Men's Toilet",
      "Merlion",
      "Mermaid Bed",
      "Mermaid Chair",
      "Mermaid Clock",
      "Mermaid Closet",
      "Mermaid Dresser",
      "Mermaid Lamp",
      "Mermaid Screen",
      "Mermaid Shelf",
      "Mermaid Sofa",
      "Mermaid Statue",
      "Mermaid Table",
      "Mermaid Vanity",
      "Merry-Go-Round",
      "Metal Guitar",
      "Metroid",
      "Metronome",
      "Mic Stand",
      "Microscope",
      "Microwave",
      "Milk Can",
      "Milk Case",
      "Mini Butterfly Table",
      "Mini Cactus",
      "Mini Circuit",
      "Mini Dharma",
      "Mini Lamp",
      "Miniature Car",
      "Minimalist Bed",
      "Minimalist Chair",
      "Minimalist Clock",
      "Minimalist Dresser",
      "Minimalist Lamp",
      "Minimalist Minitable",
      "Minimalist Ottoman",
      "Minimalist Sofa",
      "Minimalist Table",
      "Minimalist Vanity",
      "Minimalist Wardrobe",
      "Mixer",
      "Moai Statue",
      "Mobile",
      "Mochi Pestle",
      "Modern Bed",
      "Modern Cabinet",
      "Modern Chair",
      "Modern Desk",
      "Modern Dresser",
      "Modern End Table",
      "Modern Lamp",
      "Modern Sofa",
      "Modern Table",
      "Modern Wall Clock",
      "Modern Wardrobe",
      "Modern Wood Bed",
      "Modern Wood Chair",
      "Modern Wood Chest",
      "Modern Wood Clock",
      "Modern Wood Closet",
      "Modern Wood Lamp",
      "Modern Wood Shelf",
      "Modern Wood Sofa",
      "Modern Wood Stool",
      "Modern Wood Table",
      "Modern Wood TV",
      "Moon",
      "Mop",
      "Morning Glory",
      "Moth Orchid",
      "Mountain Bike",
      "Mountain Standee",
      "Mouth of Truth",
      "Mr. Flamingo",
      "Mrs. Flamingo",
      "Mugho Bonsai",
      "Mummy's Casket",
      "Museum Chair",
      "Museum Model",
      "Mush Bed",
      "Mush Chair",
      "Mush Closet",
      "Mush Dresser",
      "Mush End Table",
      "Mush Hanger",
      "Mush Lamp",
      "Mush Stool",
      "Mush Table",
      "Mush TV",
      "Mush Wall Lamp",
      "Music Stand",
      "Neon Sign",
      "Neutral Corner",
      "New Year's Noodles",
      "New Year's Sunrise Lamp",
      "Nine Lamp",
      "Ninja Sword",
      "Nutcracker",
      "Octopus Chair",
      "Odd Clock",
      "Oden Hotpan",
      "Office Chair",
      "Office Desk",
      "Office Locker",
      "Ogre Mask",
      "Oil Barrel",
      "Oil Lamp",
      "Old Sewing Machine",
      "One Lamp",
      "Orange Cone",
      "Outdoor Bath",
      "Oval Clock",
      "Owl Clock",
      "Pachira",
      "Pagoda",
      "Painting Set",
      "Pansy Table",
      "Pantheon Post",
      "Papa Bear",
      "Papa Panda",
      "Paper Lantern",
      "Paper Tiger",
      "Paper Wall Lamp",
      "Partition Screen",
      "Patchwork Chair",
      "Patchwork Dresser",
      "Patchwork Lamp",
      "Patchwork Sofa",
      "Patchwork Table",
      "Paulownia Closet",
      "Pave Bed",
      "Pave Bookshelf",
      "Pave Bureau",
      "Pave Chair",
      "Pave Chest",
      "Pave Clock",
      "Pave Closet",
      "Pave End Table",
      "Pave Lamp",
      "Pave Sofa",
      "Pave Table",
      "Pawn",
      "Peacock Chair",
      "Pear Dresser",
      "Pear Wardrobe",
      "Pendulum Clock",
      "Pepper Mill",
      "Phone Box",
      "Phonograph",
      "Pickle Jar",
      "Picnic Basket",
      "Picnic Table",
      "Piggy Bank",
      "Pikmin",
      "Pinball Machine",
      "Pine Bonsai",
      "Pine Chair",
      "Pine Table",
      "Pineapple Bed",
      "Pink Velvet Stool",
      "Pipe",
      "Pipe Organ",
      "Pipe Stool",
      "Pirate's Armor",
      "Planter",
      "Plate Armor",
      "Plum Bonsai",
      "Podium",
      "Poinsettia",
      "Polka-Dot Bed",
      "Polka-Dot Chair",
      "Polka-Dot Clock",
      "Polka-Dot Closet",
      "Polka-Dot Dresser",
      "Polka-Dot Lamp",
      "Polka-Dot Low Table",
      "Polka-Dot Sofa",
      "Polka-Dot Stool",
      "Polka-Dot Table",
      "Polka-Dot TV",
      "Ponderosa Bonsai",
      "Pop-up Book",
      "Popcorn Machine",
      "Portable Toilet",
      "Post-Office Poster",
      "Poster Stand",
      "Pot Rack",
      "Potbelly Stove",
      "Pothos",
      "Potted Ivy",
      "Potty",
      "Princess Bed",
      "Princess Cage",
      "Princess Chair",
      "Princess Chest",
      "Princess Clock",
      "Princess Closet",
      "Princess Curio",
      "Princess Dresser",
      "Princess Lamp",
      "Princess Sofa",
      "Princess Table",
      "Propane Stove",
      "Puffer-Fish TV",
      "Pyramid",
      "Queen",
      "Quince Bonsai",
      "Raccoon Figurine",
      "Radiator",
      "Ranch Armchair",
      "Ranch Bed",
      "Ranch Bookcase",
      "Ranch Chair",
      "Ranch Couch",
      "Ranch Dresser",
      "Ranch Hutch",
      "Ranch Table",
      "Ranch Tea Table",
      "Ranch Wall Rack",
      "Ranch Wardrobe",
      "Range",
      "Raven Pole",
      "Reception Table",
      "Record Player",
      "Red Corner",
      "Red Vase",
      "Red-Snapper Sofa",
      "Red-Tasseled Lantern",
      "Reel-to-Reel",
      "Refrigerator",
      "Regal Armoire",
      "Regal Bed",
      "Regal Bookcase",
      "Regal Chair",
      "Regal Clock",
      "Regal Dresser",
      "Regal Lamp",
      "Regal Sofa",
      "Regal Table",
      "Regal Vanity",
      "Regal Wall Lamp",
      "Resetti Model",
      "Retro Fridge",
      "Retro Stereo",
      "Retro TV",
      "Reversi Piece",
      "Revolving Spice Rack",
      "Rice Cake",
      "Rice Cooker",
      "Right Platform",
      "Righty Desk",
      "Ringside Table",
      "Robo-Bed",
      "Robo-Chair",
      "Robo-Clock",
      "Robo-Closet",
      "Robo-Dresser",
      "Robo-Lamp",
      "Robo-Sofa",
      "Robo-Stereo",
      "Robo-Table",
      "Robo-TV",
      "Robo-Wall Clock",
      "Rock Guitar",
      "Rocket",
      "Rocking Chair",
      "Rocking Horse",
      "Rococo Bed",
      "Rococo Candlestick",
      "Rococo Chair",
      "Rococo Clock",
      "Rococo Dresser",
      "Rococo Lamp",
      "Rococo Shelf",
      "Rococo Sofa",
      "Rococo Table",
      "Rococo Vanity",
      "Rococo Wardrobe",
      "Rook",
      "Rooster of Barcelos",
      "Rope Partition",
      "Rose Sofa",
      "Round Cactus",
      "Round Clock",
      "Round Mini Cactus",
      "Rubber Tree",
      "S.S. Dolphin",
      "Saddle Fence",
      "Safe",
      "Sailboat Model",
      "Salad Bar",
      "Samgyetang",
      "Samurai Suit",
      "Sand Castle",
      "Sandbag",
      "Sanshin",
      "Satellite",
      "Sawhorse",
      "Scale",
      "Scarecrow",
      "School Chair",
      "School Desk",
      "School Speaker",
      "Science Table",
      "Sconce",
      "Scoreboard",
      "Screen",
      "Sea Globe",
      "Sea-Anemone Bed",
      "Server",
      "Seven Lamp",
      "Sewing Machine",
      "Shamrock Clock",
      "Shaved-Ice Maker",
      "Ship Cannon",
      "Ship Compass",
      "Shogi Board",
      "Shogi Piece",
      "Shopping Cart",
      "Shower",
      "Shower Stall",
      "Silver Bug Trophy",
      "Silver Fish Trophy",
      "Silver HHA Plaque",
      "Silver HHA Trophy",
      "Simple Armchair",
      "Simple Kettle",
      "Simple Love Seat",
      "Sink",
      "Siphon",
      "Sitar",
      "Six Lamp",
      "Skeleton",
      "Skeleton Figurine",
      "Sketchbook",
      "Ski Rack",
      "Slalom Gate",
      "Sleek Bed",
      "Sleek Chair",
      "Sleek Clock",
      "Sleek Closet",
      "Sleek Dresser",
      "Sleek Lamp",
      "Sleek Side Table",
      "Sleek Sideboard",
      "Sleek Sofa",
      "Sleek Stereo",
      "Sleek Table",
      "Sleeping Bag",
      "Sleigh",
      "Slide Puzzle",
      "Sloppy Bed",
      "Sloppy Chair",
      "Sloppy Clock",
      "Sloppy Closet",
      "Sloppy Dresser",
      "Sloppy Lamp",
      "Sloppy Sink",
      "Sloppy Sofa",
      "Sloppy Stereo",
      "Sloppy Table",
      "Sloppy TV",
      "Small Igloo",
      "Small LED Display",
      "Small Magazine Rack",
      "Small Space Console",
      "Small Spotlight",
      "Smoker",
      "Snail Clock",
      "Snake Plant",
      "Snow Bunny",
      "Snow Globe",
      "Snow Machine",
      "Snowboard",
      "Snowman",
      "Snowman Bed",
      "Snowman Chair",
      "Snowman Clock",
      "Snowman Dresser",
      "Snowman Fridge",
      "Snowman Lamp",
      "Snowman Matryoshka",
      "Snowman Sofa",
      "Snowman Table",
      "Snowman TV",
      "Snowman Vanity",
      "Snowman Wardrobe",
      "Snowmobile",
      "Soda Case",
      "Soda Fountain",
      "Soft-Serve Lamp",
      "Songpyeon",
      "Spa Chair",
      "Space Captain's Seat",
      "Space Console",
      "Space Heater",
      "Space Shuttle",
      "Space Station",
      "Spaceman Sam",
      "Speed Bag",
      "Spherical Radar",
      "Sphinx",
      "Spiderweb Clock",
      "Spinning Wheel",
      "Spooky Bed",
      "Spooky Bookcase",
      "Spooky Chair",
      "Spooky Clock",
      "Spooky Dresser",
      "Spooky Lamp",
      "Spooky Sofa",
      "Spooky Table",
      "Spooky Vanity",
      "Spooky Wall Lamp",
      "Spooky Wardrobe",
      "Sprinkler",
      "Squid Chair",
      "Stadiometer",
      "Stag-Beetle Chair",
      "Stained Glass",
      "Stained-Glass Lamp",
      "Stair Dresser",
      "Standing Spotlight",
      "Star Globe",
      "Star Projector",
      "Statue of Liberty",
      "Steamed Bun Case",
      "Steamroller",
      "Stepladder",
      "Stewpot",
      "Stool",
      "Storage Case",
      "Storefront",
      "Stove",
      "Stripe Bathroom Sink",
      "Stripe Bed",
      "Stripe Chair",
      "Stripe Clock",
      "Stripe Closet",
      "Stripe Dresser",
      "Stripe Lamp",
      "Stripe Shelf",
      "Stripe Sofa",
      "Stripe Table",
      "Stripe TV",
      "Striped Cone",
      "Stroller",
      "Stuffed Stocking",
      "Stump Stool",
      "Sunflower",
      "Sunflower Stereo",
      "Super Mushroom",
      "Super Star",
      "Super Toilet",
      "Surfboard",
      "Surveillance Camera",
      "Sushi Platter",
      "Sweets Bed",
      "Sweets Bookcase",
      "Sweets Chair",
      "Sweets Closet",
      "Sweets Dresser",
      "Sweets Lamp",
      "Sweets Minilamp",
      "Sweets Minitable",
      "Sweets Player",
      "Sweets Sofa",
      "Sweets Table",
      "Sword",
      "Table Lamp",
      "Tabletop Game",
      "Taiko Drum",
      "Tall Cactus",
      "Tall Display Case",
      "Tall Lantern",
      "Tall Mini Cactus",
      "Tangerine Chair",
      "Tanuki Wall Clock",
      "Tape Deck",
      "Tapestry",
      "Tatami Bed",
      "Tea Set",
      "Tea Table",
      "Tea Tansu",
      "Tea Vase",
      "Teacher's Chair",
      "Teacher's Desk",
      "Telescope",
      "Ten Billion Barrel",
      "Tennis Table",
      "Theremin",
      "Thermohygrometer",
      "Three Lamp",
      "Throne",
      "Tiki Torch",
      "Time Clock",
      "Timpano Drum",
      "Toaster",
      "Toilet",
      "Tokonoma",
      "Tower of Pisa",
      "Toy Camera",
      "Traffic Cone",
      "Train Set",
      "Trash Bin",
      "Trash Can",
      "Treadmill",
      "Treasure Chest",
      "Tree Standee",
      "Tribal Mask",
      "Tricycle",
      "Triforce",
      "Triple Bananas",
      "Triple Red Shells",
      "Trunk",
      "Trunk Measure",
      "Tuk-Tuk",
      "Tulip Dresser",
      "Tumbleweed",
      "Turkey",
      "Turntable",
      "TV Camera",
      "TV with VCR",
      "Twelve-Grape Plate",
      "Two Lamp",
      "Typewriter",
      "Ukulele",
      "Ultra Hand",
      "Ultra Machine",
      "Ultra Scope",
      "Unknown Machine",
      "Upright Piano",
      "Upright Vacuum",
      "Vacuum Cleaner",
      "Vaulting Horse",
      "Veggie Basket",
      "Ventilation Fan",
      "Vibraphone",
      "Vintage Camera",
      "Vintage Radio",
      "Vintage Telephone",
      "Vintage Telescope",
      "Violet Screen",
      "Violin",
      "Virtual Boy",
      "Vision Tester",
      "Volleyball Net",
      "Wagon Wheel",
      "Wall Fan",
      "Wall Flowerpot",
      "Wall-Mounted Monitor",
      "Wall-Mounted Speaker",
      "Washbasin",
      "Washbasin",
      "Washer/Dryer",
      "Washing Machine",
      "Water Bird",
      "Water Cooler",
      "Watering Trough",
      "Watermelon Chair",
      "Watermelon Table",
      "Wave Breaker",
      "Wedding Cake",
      "Weeping Fig",
      "Weight Bench",
      "Well",
      "Western Fence",
      "Wet-Road Sign",
      "Wheat Bundle",
      "Wheat Field",
      "Whirlpool Bath",
      "White Katana",
      "White Pot",
      "Whiteboard",
      "Wide-Screen TV",
      "Wii Balance Board",
      "Wobbelina",
      "Wooden Box",
      "Wooden Stool",
      "World Map",
      "Writing Chair",
      "Writing Desk",
      "Yellow Certificate",
      "Yoshi's Egg",
      "Yut Board",
      "Zero Lamp",
      "Zodiac Boar",
      "Zodiac Dog",
      "Zodiac Dragon",
      "Zodiac Goat",
      "Zodiac Horse",
      "Zodiac Monkey",
      "Zodiac Ox",
      "Zodiac Rabbit",
      "Zodiac Rat",
      "Zodiac Rooster",
      "Zodiac Snake"
    ]
  };

  $('#q').typeahead({
    minLength: 1,
    order: "asc",
    group: true,
    groupMaxItem: 5,
    hint: true,
    filter: "All",
    cache: false,
    selector: {
      filter: "input-group-btn",
      filterButton: "btn btn-default",
      dropdown: "dropdown-menu dropdown-menu-right",
      list: "dropdown-menu",
      hint: "form-control",
      highlight: true
    },
    source: {
      Selling: {
        data: data.selling
      },
      Buying: {
        data: data.buying
      }
    },
    callback: {
      onInit: null,
      onResult: null,
      onMouseEnter: null,
      onMouseLeave: null,
      onClick: function (node, a, obj, e) {

        console.log("You Selected");
      },
      onSubmit: function (node, form, obj, e) {

        console.log("You Submited");

      }
    },
    debug: true
  });


  /* Fading in */
  $('body').fadeIn(function () {

    $('#logTitlContain').effect("bounce", {direction: 'up', distance: 100, times: 4}, 500, function () {
      $('#q').effect("highlight", {}, 1000);
    });
  });

});
